#pragma once

namespace GodEngine
{
	typedef enum GOD_VERTEX_DATA_TYPE
	{
		GVDT_FLOAT1		= 0,
		GVDT_FLOAT2		= 1,
		GVDT_FLOAT3		= 2,
		GVDT_FLOAT4		= 3,
		GVDT_D3DCOLOR	= 4,
		GVDT_UBYTE4		= 5,
		GVDT_SHORT2		= 6,
		GVDT_SHORT4		= 7,
		GVDT_UBYTE4N	= 8,
		GVDT_SHORT2N	= 9,
		GVDT_SHORT4N	= 10,
		GVDT_USHORT2N	= 11,
		GVDT_USHORT4N	= 12,
		GVDT_UDEC3		= 13,
		GVDT_DEC3N		= 14,
		GVDT_FLOAT16_2	= 15,
		GVDT_FLOAT16_4	= 16,
		GVDT_UNUSED		= 17
	}GOD_VERTEX_DATA_TYPE;

	typedef enum GOD_VERTEX_USAGE_TYPE
	{
		GVUT_POSITION = 0,
		GVUT_BLENDWEIGHT = 1,
		GVUT_BLENDINDICES = 2,
		GVUT_NORMAL = 3,
		GVUT_PSIZE = 4,
		GVUT_TEXCOORD = 5,
		GVUT_TANGENT = 6,
		GVUT_BINORMAL = 7,
		GVUT_TESSFACTOR = 8,
		GVUT_POSITIONT = 9,
		GVUT_COLOR = 10,
		GVUT_FOG = 11,
		GVUT_DEPTH = 12,
		GVUT_SAMPLE = 13
	}GOD_VERTEX_USAGE_TYPE;

	typedef enum GOD_VERTEX_METHOD
	{
		GVM_DEFAULT = 0,
		GVM_PARTIALU = 1,
		GVM_PARTIALV = 2,
		GVM_CROSSUV = 3,
		GVM_UV = 4,
		GVM_LOOKUP = 5,
		GVM_LOOKUPPRESAMPLED = 6
	}GOD_VERTEX_METHOD;
}